import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/general/header";
import Footer from "@/components/general/footer";
import Providers from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          <div className="min-h-screen text-signal-black bg-gradient-to-br from-white to-stone-white-3">
            {children}
          </div>
          <div id="modal-root" />
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
